# Generated by Django 4.1.2 on 2022-10-22 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('date_created', models.DateField(default=datetime.datetime(2022, 10, 22, 21, 35, 38, 224795))),
            ],
        ),
    ]
