# Generated by Django 4.1.2 on 2022-10-22 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
