# Generated by Django 4.1.7 on 2023-03-04 11:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_games_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_created',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='imgURL',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='GamesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_created', models.DateField(default=datetime.date.today, editable=False)),
                ('gameName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.games')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'gameName')},
            },
        ),
    ]
